vim.g.colors_name = "custom-color"
vim.cmd("hi clear")
vim.cmd("syntax reset")

vim.o.background = "dark"
vim.o.termguicolors = true

local background = "#010316" -- "NvimDarkGrey2"
local highlight = "#4f4d64" -- "NvimDarkGrey4"
local semihighlight = "#2c2a3a" -- "NvimDarkGrey3"

local text = "#efefff" -- "NvimLightGrey2"
local comment = "#7b7895" -- "NvimLightGrey4"
local nontext = "#44415a" -- "NvimDarkGrey3"

local accent1 = "#cab5ff" -- "NvimLightCyan"
local accent2 = "#85a0f8" -- "NvimLightBlue"
local accent3 = "#f9bca4" -- "NvimLightGreen"

local groups = {

    -- Main colors

    ["Normal"] = { fg = text, bg = background },
    ["Visual"] = { bg = highlight },
    ["ColorColumn"] = { bg = highlight },
    ["CursorLine"] = { bg = semihighlight },
    ["CursorColumn"] = { bg = semihighlight },
    ["Search"] = { fg = background, bg = accent1 },
    ["CurSearch"] = { fg = accent1, bg = highlight, bold = true },
    ["StatusLine"] = { fg = background, bg = comment },
    ["StatusLineNC"] = { fg = background, bg = comment },

    ["Comment"] = { fg = comment },
    ["NonText"] = { fg = nontext },
    ["LineNr"] = { fg = nontext },
    ["SignColumn"] = { fg = nontext },
    ["SpecialKey"] = { fg = nontext },

    ["Delimiter"] = { fg = text },
    ["Operator"] = { fg = text },
    ["@variable"] = { fg = text },
    ["PreProc"] = { fg = text },

    ["Title"] = { fg = accent1 },
    ["Directory"] = { fg = accent1 },
    ["Statement"] = { fg = accent1 },
    ["Type"] = { fg = accent1 },
    ["Special"] = { fg = accent1 },
    ["Function"] = { fg = accent2 },
    ["Identifier"] = { fg = accent2 },
    ["Constant"] = { fg = accent3 },
    ["String"] = { fg = accent3 },

    ["Todo"] = { fg = text, bold = true },
    ["Folded"] = { fg = comment, bg = background },
    ["MatchParen"] = { bold = true, bg = highlight },
    ["Conceal"] = { fg = "NvimDarkGrey4" },
    ["NormalFloat"] = { bg = "NvimDarkGrey1" },
    ["QuickFixLine"] = { fg = "NvimLightCyan" },

    ["WinBar"] = { bold = true, fg = comment, bg = background },
    ["WinBarNC"] = { bold = true, fg = comment, bg = background },
    ["Pmenu"] = { bg = semihighlight },
    ["PmenuThumb"] = { bg = highlight },
    ["FloatShadow"] = { bg = highlight, blend = 80 },
    ["FloatShadowThrough"] = { bg = highlight, blend = 100 },

    ["RedrawDebugClear"] = { bg = "NvimDarkYellow" },
    ["RedrawDebugComposed"] = { bg = "NvimDarkGreen" },
    ["RedrawDebugRecompose"] = { bg = "NvimDarkRed" },
    ["Changed"] = { fg = "NvimLightCyan" },
    ["Added"] = { fg = "NvimLightGreen" },
    ["Removed"] = { fg = "NvimLightRed" },
    ["DiffText"] = { fg = "NvimLightGrey1", bg = "NvimDarkCyan" },
    ["DiffChange"] = { fg = "NvimLightGrey1", bg = "NvimDarkGrey4" },
    ["DiffAdd"] = { fg = "NvimLightGrey1", bg = "NvimDarkGreen" },
    ["DiffDelete"] = { fg = "NvimLightRed", bold = true },

    ["SpellBad"] = { undercurl = true, sp="NvimLightRed" },
    ["SpellCap"] = { undercurl = true, sp="NvimLightYellow" },
    ["SpellRare"] = { undercurl = true, sp="NvimLightCyan" },
    ["SpellLocal"] = { undercurl = true, sp="NvimLightGreen" },
    ["ErrorMsg"] = { fg = "NvimLightRed" },
    ["WarningMsg"] = { fg = "NvimLightYellow" },
    ["MoreMsg"] = { fg = "NvimLightCyan" },
    ["Question"] = { fg = "NvimLightCyan" },
    ["ModeMsg"] = { fg = "NvimLightGreen" },
    ["DiagnosticError"] = { fg = "NvimLightRed" },
    ["DiagnosticWarn"] = { fg = "NvimLightYellow" },
    ["DiagnosticInfo"] = { fg = "NvimLightCyan" },
    ["DiagnosticHint"] = { fg = "NvimLightBlue" },
    ["DiagnosticOk"] = { fg = "NvimLightGreen" },
    ["DiagnosticUnderlineError"] = { underline = true, sp = "NvimLightRed" },
    ["DiagnosticUnderlineWarn"] = { underline = true, sp = "NvimLightYellow" },
    ["DiagnosticUnderlineInfo"] = { underline = true, sp = "NvimLightCyan" },
    ["DiagnosticUnderlineHint"] = { underline = true, sp = "NvimLightBlue" },
    ["DiagnosticUnderlineOk"] = { underline = true, sp = "NvimLightGreen" },
    ["DiagnosticDeprecated"] = { strikethrough = true, sp="NvimLightRed" },

    ["Error"] = { fg = "NvimLightGrey1", bg = "NvimDarkRed" },
    ["NvimInternalError"] = { fg = "Red", bg = "Red" },

    -- ["@text.title.1.marker.markdown"] = { fg = accent1, bg = semihighlight },
    -- ["@text.title.2.marker.markdown"] = { fg = accent2, bg = semihighlight },
    -- ["@text.title.3.marker.markdown"] = { fg = accent3, bg = semihighlight },
    -- ["@text.title.4.marker.markdown"] = { fg = accent1, bg = semihighlight },
    -- ["@text.title.5.marker.markdown"] = { fg = accent2, bg = semihighlight },
    -- ["@text.title.6.marker.markdown"] = { fg = accent3, bg = semihighlight },

    -- ["@org.headline.level1"] = { fg = accent1, bg = semihighlight },
    -- ["@org.headline.level2"] = { fg = accent2, bg = semihighlight },
    -- ["@org.headline.level3"] = { fg = accent3, bg = semihighlight },
    -- ["@org.headline.level4"] = { fg = accent1, bg = semihighlight },
    -- ["@org.headline.level5"] = { fg = accent2, bg = semihighlight },
    -- ["@org.headline.level6"] = { fg = accent3, bg = semihighlight },
    -- ["@org.headline.level7"] = { fg = accent1, bg = semihighlight },
    -- ["@org.headline.level8"] = { fg = accent2, bg = semihighlight },

    -- ["@org.bullet"] = { fg = accent1 },
    -- ["@org.hyperlink"] = { fg = accent2 },
    -- ["@org.verbatim"] = { fg = accent3 },
    -- ["@org.code"] = { bg = semihighlight },

    -- Modifiers

    ["TermCursor"] = { reverse = true },
    ["CursorLineNr"] = { bold = true },
    ["PmenuSel"] = { reverse = true, underline = true, blend = 0 },
    ["PmenuMatch"] = { bold = true },
    ["PmenuMatchSel"] = { bold = true },
    ["TabLineSel"] = { bold = true },
    ["Cursor"] = { fg = "bg", bg = "fg" },
    ["RedrawDebugNormal"] = { reverse = true },
    ["Underlined"] = { underline = true },
    ["lCursor"] = { fg = "bg", bg = "fg" },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading.1.delimiter.vimdoc"] = { underline = true, nocombine = true, fg = "bg", bg = "bg", sp="fg" },
    ["@markup.heading.2.delimiter.vimdoc"] = { underline = true, nocombine = true, fg = "bg", bg = "bg", sp="fg" },

    -- Links

    ["EndOfBuffer"] = { link = "NonText" },
    ["IncSearch"] = { link = "CurSearch" },
    ["LineNrAbove"] = { link = "LineNr" },
    ["LineNrBelow"] = { link = "LineNr" },
    ["CursorLineSign"] = { link = "SignColumn" },
    ["CursorLineFold"] = { link = "FoldColumn" },
    ["WinSeparator"] = { link = "Normal" },
    ["VertSplit"] = { link = "WinSeparator" },
    ["WildMenu"] = { link = "PmenuSel" },
    ["FoldColumn"] = { link = "SignColumn" },
    ["PmenuKind"] = { link = "Pmenu" },
    ["PmenuKindSel"] = { link = "PmenuSel" },
    ["PmenuExtra"] = { link = "Pmenu" },
    ["PmenuExtraSel"] = { link = "PmenuSel" },
    ["PmenuSbar"] = { link = "Pmenu" },
    ["TabLine"] = { link = "StatusLineNC" },
    ["TabLineFill"] = { link = "TabLine" },
    ["Whitespace"] = { link = "NonText" },
    ["MsgSeparator"] = { link = "StatusLine" },
    ["FloatBorder"] = { link = "NormalFloat" },
    ["FloatTitle"] = { link = "Title" },
    ["FloatFooter"] = { link = "FloatTitle" },
    ["StatusLineTerm"] = { link = "StatusLine" },
    ["StatusLineTermNC"] = { link = "StatusLineNC" },
    ["CursorIM"] = { link = "Cursor" },
    ["Substitute"] = { link = "Search" },
    ["VisualNOS"] = { link = "Visual" },
    ["Character"] = { link = "Constant" },
    ["Number"] = { link = "Constant" },
    ["Boolean"] = { link = "Constant" },
    ["Float"] = { link = "Number" },
    ["Conditional"] = { link = "Statement" },
    ["Repeat"] = { link = "Statement" },
    ["Label"] = { link = "Statement" },
    ["Keyword"] = { link = "Statement" },
    ["Exception"] = { link = "Statement" },
    ["Include"] = { link = "PreProc" },
    ["Define"] = { link = "PreProc" },
    ["Macro"] = { link = "PreProc" },
    ["PreCondit"] = { link = "PreProc" },
    ["StorageClass"] = { link = "Type" },
    ["Structure"] = { link = "Type" },
    ["Typedef"] = { link = "Type" },
    ["Tag"] = { link = "Special" },
    ["SpecialChar"] = { link = "Special" },
    ["SpecialComment"] = { link = "Special" },
    ["Debug"] = { link = "Special" },
    ["Ignore"] = { link = "Normal" },
    ["LspCodeLens"] = { link = "NonText" },
    ["LspCodeLensSeparator"] = { link = "LspCodeLens" },
    ["LspInlayHint"] = { link = "NonText" },
    ["LspReferenceRead"] = { link = "LspReferenceText" },
    ["LspReferenceText"] = { link = "Visual" },
    ["LspReferenceWrite"] = { link = "LspReferenceText" },
    ["LspReferenceTarget"] = { link = "LspReferenceText" },
    ["LspSignatureActiveParameter"] = { link = "Visual" },
    ["SnippetTabstop"] = { link = "Visual" },
    ["DiagnosticFloatingError"] = { link = "DiagnosticError" },
    ["DiagnosticFloatingWarn"] = { link = "DiagnosticWarn" },
    ["DiagnosticFloatingInfo"] = { link = "DiagnosticInfo" },
    ["DiagnosticFloatingHint"] = { link = "DiagnosticHint" },
    ["DiagnosticFloatingOk"] = { link = "DiagnosticOk" },
    ["DiagnosticVirtualTextError"] = { link = "DiagnosticError" },
    ["DiagnosticVirtualTextWarn"] = { link = "DiagnosticWarn" },
    ["DiagnosticVirtualTextInfo"] = { link = "DiagnosticInfo" },
    ["DiagnosticVirtualTextHint"] = { link = "DiagnosticHint" },
    ["DiagnosticVirtualTextOk"] = { link = "DiagnosticOk" },
    ["DiagnosticVirtualLinesError"] = { link = "DiagnosticError" },
    ["DiagnosticVirtualLinesWarn"] = { link = "DiagnosticWarn" },
    ["DiagnosticVirtualLinesInfo"] = { link = "DiagnosticInfo" },
    ["DiagnosticVirtualLinesHint"] = { link = "DiagnosticHint" },
    ["DiagnosticVirtualLinesOk"] = { link = "DiagnosticOk" },
    ["DiagnosticSignError"] = { link = "DiagnosticError" },
    ["DiagnosticSignWarn"] = { link = "DiagnosticWarn" },
    ["DiagnosticSignInfo"] = { link = "DiagnosticInfo" },
    ["DiagnosticSignHint"] = { link = "DiagnosticHint" },
    ["DiagnosticSignOk"] = { link = "DiagnosticOk" },
    ["DiagnosticUnnecessary"] = { link = "Comment" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.parameter.builtin"] = { link = "Special" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@module"] = { link = "Structure" },
    ["@module.builtin"] = { link = "Special" },
    ["@label"] = { link = "Label" },
    ["@string"] = { link = "String" },
    ["@string.regexp"] = { link = "@string.special" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.escape"] = { link = "@string.special" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Special" },
    ["@attribute"] = { link = "Macro" },
    ["@attribute.builtin"] = { link = "Special" },
    ["@property"] = { link = "Identifier" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@constructor"] = { link = "Special" },
    ["@operator"] = { link = "Operator" },
    ["@keyword"] = { link = "Keyword" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Special" },
    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { link = "DiagnosticError" },
    ["@comment.warning"] = { link = "DiagnosticWarn" },
    ["@comment.note"] = { link = "DiagnosticInfo" },
    ["@comment.todo"] = { link = "Todo" },
    ["@markup"] = { link = "Special" },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { link = "Underlined" },
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@tag"] = { link = "Tag" },
    ["@tag.builtin"] = { link = "Special" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.event"] = { link = "@type" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.macro"] = { link = "@constant.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.modifier"] = { link = "@type.qualifier" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.deprecated"] = { link = "DiagnosticDeprecated" },
    ["NvimAssignment"] = { link = "Operator" },
    ["NvimPlainAssignment"] = { link = "NvimAssignment" },
    ["NvimAugmentedAssignment"] = { link = "NvimAssignment" },
    ["NvimAssignmentWithAddition"] = { link = "NvimAugmentedAssignment" },
    ["NvimAssignmentWithSubtraction"] = { link = "NvimAugmentedAssignment" },
    ["NvimAssignmentWithConcatenation"] = { link = "NvimAugmentedAssignment" },
    ["NvimOperator"] = { link = "Operator" },
    ["NvimUnaryOperator"] = { link = "NvimOperator" },
    ["NvimUnaryPlus"] = { link = "NvimUnaryOperator" },
    ["NvimUnaryMinus"] = { link = "NvimUnaryOperator" },
    ["NvimNot"] = { link = "NvimUnaryOperator" },
    ["NvimBinaryOperator"] = { link = "NvimOperator" },
    ["NvimComparison"] = { link = "NvimBinaryOperator" },
    ["NvimComparisonModifier"] = { link = "NvimComparison" },
    ["NvimBinaryPlus"] = { link = "NvimBinaryOperator" },
    ["NvimBinaryMinus"] = { link = "NvimBinaryOperator" },
    ["NvimConcat"] = { link = "NvimBinaryOperator" },
    ["NvimConcatOrSubscript"] = { link = "NvimConcat" },
    ["NvimOr"] = { link = "NvimBinaryOperator" },
    ["NvimAnd"] = { link = "NvimBinaryOperator" },
    ["NvimMultiplication"] = { link = "NvimBinaryOperator" },
    ["NvimDivision"] = { link = "NvimBinaryOperator" },
    ["NvimMod"] = { link = "NvimBinaryOperator" },
    ["NvimTernary"] = { link = "NvimOperator" },
    ["NvimTernaryColon"] = { link = "NvimTernary" },
    ["NvimParenthesis"] = { link = "Delimiter" },
    ["NvimLambda"] = { link = "NvimParenthesis" },
    ["NvimNestingParenthesis"] = { link = "NvimParenthesis" },
    ["NvimCallingParenthesis"] = { link = "NvimParenthesis" },
    ["NvimSubscript"] = { link = "NvimParenthesis" },
    ["NvimSubscriptBracket"] = { link = "NvimSubscript" },
    ["NvimSubscriptColon"] = { link = "NvimSubscript" },
    ["NvimCurly"] = { link = "NvimSubscript" },
    ["NvimContainer"] = { link = "NvimParenthesis" },
    ["NvimDict"] = { link = "NvimContainer" },
    ["NvimList"] = { link = "NvimContainer" },
    ["NvimIdentifier"] = { link = "Identifier" },
    ["NvimIdentifierScope"] = { link = "NvimIdentifier" },
    ["NvimIdentifierScopeDelimiter"] = { link = "NvimIdentifier" },
    ["NvimIdentifierName"] = { link = "NvimIdentifier" },
    ["NvimIdentifierKey"] = { link = "NvimIdentifier" },
    ["NvimColon"] = { link = "Delimiter" },
    ["NvimComma"] = { link = "Delimiter" },
    ["NvimArrow"] = { link = "Delimiter" },
    ["NvimRegister"] = { link = "SpecialChar" },
    ["NvimNumber"] = { link = "Number" },
    ["NvimFloat"] = { link = "NvimNumber" },
    ["NvimNumberPrefix"] = { link = "Type" },
    ["NvimOptionSigil"] = { link = "Type" },
    ["NvimOptionName"] = { link = "NvimIdentifier" },
    ["NvimOptionScope"] = { link = "NvimIdentifierScope" },
    ["NvimOptionScopeDelimiter"] = { link = "NvimIdentifierScopeDelimiter" },
    ["NvimEnvironmentSigil"] = { link = "NvimOptionSigil" },
    ["NvimEnvironmentName"] = { link = "NvimIdentifier" },
    ["NvimString"] = { link = "String" },
    ["NvimStringBody"] = { link = "NvimString" },
    ["NvimStringQuote"] = { link = "NvimString" },
    ["NvimStringSpecial"] = { link = "SpecialChar" },
    ["NvimSingleQuote"] = { link = "NvimStringQuote" },
    ["NvimSingleQuotedBody"] = { link = "NvimStringBody" },
    ["NvimSingleQuotedQuote"] = { link = "NvimStringSpecial" },
    ["NvimDoubleQuote"] = { link = "NvimStringQuote" },
    ["NvimDoubleQuotedBody"] = { link = "NvimStringBody" },
    ["NvimDoubleQuotedEscape"] = { link = "NvimStringSpecial" },
    ["NvimFigureBrace"] = { link = "NvimInternalError" },
    ["NvimSingleQuotedUnknownEscape"] = { link = "NvimInternalError" },
    ["NvimSpacing"] = { link = "Normal" },
    ["NvimInvalidSingleQuotedUnknownEscape"] = { link = "NvimInternalError" },
    ["NvimInvalid"] = { link = "Error" },
    ["NvimInvalidAssignment"] = { link = "NvimInvalid" },
    ["NvimInvalidPlainAssignment"] = { link = "NvimInvalidAssignment" },
    ["NvimInvalidAugmentedAssignment"] = { link = "NvimInvalidAssignment" },
    ["NvimInvalidAssignmentWithAddition"] = { link = "NvimInvalidAugmentedAssignment" },
    ["NvimInvalidAssignmentWithSubtraction"] = { link = "NvimInvalidAugmentedAssignment" },
    ["NvimInvalidAssignmentWithConcatenation"] = { link = "NvimInvalidAugmentedAssignment" },
    ["NvimInvalidOperator"] = { link = "NvimInvalid" },
    ["NvimInvalidUnaryOperator"] = { link = "NvimInvalidOperator" },
    ["NvimInvalidUnaryPlus"] = { link = "NvimInvalidUnaryOperator" },
    ["NvimInvalidUnaryMinus"] = { link = "NvimInvalidUnaryOperator" },
    ["NvimInvalidNot"] = { link = "NvimInvalidUnaryOperator" },
    ["NvimInvalidBinaryOperator"] = { link = "NvimInvalidOperator" },
    ["NvimInvalidComparison"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidComparisonModifier"] = { link = "NvimInvalidComparison" },
    ["NvimInvalidBinaryPlus"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidBinaryMinus"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidConcat"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidConcatOrSubscript"] = { link = "NvimInvalidConcat" },
    ["NvimInvalidOr"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidAnd"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidMultiplication"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidDivision"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidMod"] = { link = "NvimInvalidBinaryOperator" },
    ["NvimInvalidTernary"] = { link = "NvimInvalidOperator" },
    ["NvimInvalidTernaryColon"] = { link = "NvimInvalidTernary" },
    ["NvimInvalidDelimiter"] = { link = "NvimInvalid" },
    ["NvimInvalidParenthesis"] = { link = "NvimInvalidDelimiter" },
    ["NvimInvalidLambda"] = { link = "NvimInvalidParenthesis" },
    ["NvimInvalidNestingParenthesis"] = { link = "NvimInvalidParenthesis" },
    ["NvimInvalidCallingParenthesis"] = { link = "NvimInvalidParenthesis" },
    ["NvimInvalidSubscript"] = { link = "NvimInvalidParenthesis" },
    ["NvimInvalidSubscriptBracket"] = { link = "NvimInvalidSubscript" },
    ["NvimInvalidSubscriptColon"] = { link = "NvimInvalidSubscript" },
    ["NvimInvalidCurly"] = { link = "NvimInvalidSubscript" },
    ["NvimInvalidContainer"] = { link = "NvimInvalidParenthesis" },
    ["NvimInvalidDict"] = { link = "NvimInvalidContainer" },
    ["NvimInvalidList"] = { link = "NvimInvalidContainer" },
    ["NvimInvalidValue"] = { link = "NvimInvalid" },
    ["NvimInvalidIdentifier"] = { link = "NvimInvalidValue" },
    ["NvimInvalidIdentifierScope"] = { link = "NvimInvalidIdentifier" },
    ["NvimInvalidIdentifierScopeDelimiter"] = { link = "NvimInvalidIdentifier" },
    ["NvimInvalidIdentifierName"] = { link = "NvimInvalidIdentifier" },
    ["NvimInvalidIdentifierKey"] = { link = "NvimInvalidIdentifier" },
    ["NvimInvalidColon"] = { link = "NvimInvalidDelimiter" },
    ["NvimInvalidComma"] = { link = "NvimInvalidDelimiter" },
    ["NvimInvalidArrow"] = { link = "NvimInvalidDelimiter" },
    ["NvimInvalidRegister"] = { link = "NvimInvalidValue" },
    ["NvimInvalidNumber"] = { link = "NvimInvalidValue" },
    ["NvimInvalidFloat"] = { link = "NvimInvalidNumber" },
    ["NvimInvalidNumberPrefix"] = { link = "NvimInvalidNumber" },
    ["NvimInvalidOptionSigil"] = { link = "NvimInvalidIdentifier" },
    ["NvimInvalidOptionName"] = { link = "NvimInvalidIdentifier" },
    ["NvimInvalidOptionScope"] = { link = "NvimInvalidIdentifierScope" },
    ["NvimInvalidOptionScopeDelimiter"] = { link = "NvimInvalidIdentifierScopeDelimiter" },
    ["NvimInvalidEnvironmentSigil"] = { link = "NvimInvalidOptionSigil" },
    ["NvimInvalidEnvironmentName"] = { link = "NvimInvalidIdentifier" },
    ["NvimInvalidString"] = { link = "NvimInvalidValue" },
    ["NvimInvalidStringBody"] = { link = "NvimStringBody" },
    ["NvimInvalidStringQuote"] = { link = "NvimInvalidString" },
    ["NvimInvalidStringSpecial"] = { link = "NvimStringSpecial" },
    ["NvimInvalidSingleQuote"] = { link = "NvimInvalidStringQuote" },
    ["NvimInvalidSingleQuotedBody"] = { link = "NvimInvalidStringBody" },
    ["NvimInvalidSingleQuotedQuote"] = { link = "NvimInvalidStringSpecial" },
    ["NvimInvalidDoubleQuote"] = { link = "NvimInvalidStringQuote" },
    ["NvimInvalidDoubleQuotedBody"] = { link = "NvimInvalidStringBody" },
    ["NvimInvalidDoubleQuotedEscape"] = { link = "NvimInvalidStringSpecial" },
    ["NvimInvalidDoubleQuotedUnknownEscape"] = { link = "NvimInvalidValue" },
    ["NvimInvalidFigureBrace"] = { link = "NvimInvalidDelimiter" },
    ["NvimInvalidSpacing"] = { link = "ErrorMsg" },
    ["NvimDoubleQuotedUnknownEscape"] = { link = "NvimInvalidValue" },

    -- Cleared

    -- ["VisualNC"] = { cleared },
    -- ["NormalNC"] = { cleared },
    -- ["MsgArea"] = { cleared },
    -- ["ComplMatchIns"] = { cleared },
    -- ["@diff"] = { cleared },
    -- ["@lsp"] = { cleared },
}

for group, hl in pairs(groups) do
    vim.api.nvim_set_hl(0, group, hl)
end
